### PR TITLE
refactor: year chart

### PR DESCRIPTION
**Pull request by eldu**
- refactor: `YearChart.js` and `yearChart.json`
  - Now when a year is clicked, it's just highlighted

## TODOs that came from this PR
- #70
  - 🚧 Waiting on doing this functionality until after #51 
- #71
  - YES, the year chart looks weird because there are publications with missing data!!! I plan to fix this on the data side, not on this side.

## Demo
https://github.com/brown-ccv/ccv-pubs-frontend/assets/5270855/ed791925-db40-4c50-9917-b8da3aed69f9

Old 
[Screenshot 2024-02-27 at 3 50 49 PM](https://github.com/brown-ccv/ccv-pubs-frontend/assets/5270855/ed586df9-3ab6-4f53-b5a8-f67e280c74c6)
[Screenshot 2024-02-27 at 3 50 44 PM](https://github.com/brown-ccv/ccv-pubs-frontend/assets/5270855/04cf0a3f-cced-496b-90f5-e6c716acfa3c)

### CODE REVIEW

**Review by hetd54 — COMMENTED** [review]
This looks so cool! You've done a beautiful job. 

I think the month view shows the same data no matter which month you are on currently. 2024 shows 3 pubs:

Screenshot 2024-02-27 at 5 28 35 PM

But the Month view for 2024 is showing:
Screenshot 2024-02-27 at 5 29 02 PM

It was also unclear to me as a user how to return to the year view. I expected clicking on a bar within the "Month" view would result in a filter on the above table, not for it to take me back to the year view.

**Comment by eldu** [comment]
@hetd54 Amazing catch! Somehow through my refactor I messed up the filter. Here's what 2024 looks like now :) 

Screenshot 2024-02-28 at 11 38 03 AM

> It was also unclear to me as a user how to return to the year view. Should we add something visually instead of clicking on the table again?
So, this is what the previous functionality was. I'm interested into hearing ideas though !

**Comment by hetd54** [comment]
> @hetd54 Amazing catch! Somehow through my refactor I messed up the filter. Here's what 2024 looks like now :)
> 
> Screenshot 2024-02-28 at 11 38 03 AM
> > It was also unclear to me as a user how to return to the year view. Should we add something visually instead of clicking on the table again?
> 
> So, this is what the previous functionality was. I'm interested into hearing ideas though !

Data looks as expected now!

For an idea, maybe a " ← Back to Year View" link somewhere beneath the title, or even below the graph? That way you can reserve the action of clicking on the bar for the table filter feature later.

**Comment by eldu** [comment]
- Remove month view
- Highlight selectedYear

**Comment by hetd54** [comment]
@eldu  I would expect that clicking on a bar to highlight it instantly, but if a bar is already highlighted it unhighlights onclick no matter where on the graph you've clicked:

https://github.com/brown-ccv/ccv-pubs-frontend/assets/35639529/c1e074a7-84a5-4941-b6b4-86afa0be0289

**Review by RobertGemmaJr — APPROVED** [review]

**Pull request merged**
