### PR TITLE
refactor: add pub

### PR DESCRIPTION
**Pull request by eldu**
- deprecates keycloak, redux-saga
- refactors add pub form into modal
  - changes search to only use doi, and not also doi url. Decision was made to streamline rather than support multiple inputs
  - valid searched publication populates the manual form for users to verify and edit
  - adds yup validation and formik error messages on all fields
  - handles whether publication already exists in our database
  - handles results from fetching publication
  - handles undefined values by basically setting every field to have to be defined (firebase hates undefined)
- refactors firebase publication document into a standalone document per publication
- refactors fetching publications into a custom react hook that watches the publications collection and automatically updates the redux store
- loading and disabled form
- fix css weirdness... i'm so sorry this is in this pr

⚠️ Temporary security risk: I updated the firebase rules for the "publications" collection to allow anyone to write to it ⚠️
Until #49 

[Search Form](https://github.com/brown-ccv/ccv-pubs-frontend/assets/5270855/6c9f60a7-b4d6-4055-a74e-880f84c95f76)
[Manual Form](https://github.com/brown-ccv/ccv-pubs-frontend/assets/5270855/329858b9-0235-483c-9caf-1fa742b69716)

### CODE REVIEW

**Comment by eldu** [comment]
Returning to draft because I want to fix the reads

**Comment by eldu** [comment]
I added in some date stuff such that it shows the 10 most recent publications added to the database. Mostly so that this can show off the things I did in this PR for adding in the publication. So when you add you'll see the page automatically update!

**Comment by eldu** [comment]
Opened an issue to investigate scope 
https://github.com/brown-ccv/ccv-pubs-frontend/issues/67

**Review by hetd54 — APPROVED** [review]
Looks amazing! My only thought is that the DOI probably does not need to be sortable.

This is probably something you will implement in the future, but noting that on mobile it's a bit cramped: 
Screenshot 2024-02-14 at 3 52 07 PM

**Comment by eldu** [comment]
> Looks amazing! My only thought is that the DOI probably does not need to be sortable.
> 
> This is probably something you will implement in the future, but noting that on mobile it's a bit cramped: Screenshot 2024-02-14 at 3 52 07 PM

I'll add this to this issue when the table gets reworked into tanstack ! https://github.com/brown-ccv/ccv-pubs-frontend/issues/51

**Pull request merged**
